### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Paerakeeter** [fgebhart/mapa-streamlit#12]
Hello,
For some reason, whenever I try to access this app, it shows up with this big white screen saying the words "oh no", then instructs me to contact support. I could not find an error code/identifier so I do apologize, I hope to hear from you soon.

-pan

**Comment by fgebhart** [comment]
Hey @Paerakeeter 

thanks for reaching out. I assume error might be related to a combination of long running tasks of my app (like fetching geotiffs and computing STLs) and checking the health status of streamlit apps by streamlit cloud. I need to investigate this further to get a better understanding of the issue. Maybe it crashed only because to the time you wanted to access it, hundreds of other people also tried the same.

However, I have rebooted the app and it seems to be running stable now. Feel free to again reach out if it crashed.
